# Exclude external CSS files that aren't written by me
exclude: 'src/scss/vendor/**'

# Scss lint settings
linters:
  ColorKeyword:
    enabled: false
  DeclarationOrder:
    enabled: false
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space
    width: 2
  LeadingZero:
    enabled: true
    style: include_zero
  NestingDepth:
    enabled: true
    max_depth: 3
  PropertySortOrder:
    enabled: false
  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
